apiVersion: v1
kind: Pod
metadata: 
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: voting-app
      image: repo/examplevotingapp_vote:v1
      ports:
        - containerPort: 80
      securityContext:
        # Run the container as a non-root user with UID 1000
        runAsUser: 1000
        # Prevent processes in the container from gaining additional privileges
        allowPrivilegeEscalation: false
        # Make the root filesystem read-only
        readOnlyRootFilesystem: true
      readinessProbe:
        # Define an HTTP GET request for the readiness probe
        httpGet:
          path: /
          port: 80
        # Time to wait before performing the first probe
        initialDelaySeconds: 5
        # How often to perform the probe
        periodSeconds: 10
        # Probe timeout duration
        timeoutSeconds: 5
        # Number of consecutive successes required to mark the container as ready
        successThreshold: 1
        # Number of consecutive failures required to mark the container as not ready
        failureThreshold: 3
      livenessProbe:
        # Define an HTTP GET request for the liveness probe
        httpGet:
          path: /
          port: 80
        # Time to wait before performing the first probe
        initialDelaySeconds: 15
        # How often to perform the probe
        periodSeconds: 20
        # Probe timeout duration
        timeoutSeconds: 5
        # Number of consecutive successes required to mark the container as alive
        successThreshold: 1
        # Number of consecutive failures required to mark the container as unhealthy
        failureThreshold: 3

			  